### ISSUE TITLE
[BUG] Cookie banner reappears after refresh

### ISSUE THREAD

**Issue by paphonb** [thinc-org/cugetreg#377]
**Describe the bug**
After choosing not to opt in to analytics cookies, the cookie banner reappears after refreshing the page.

**To Reproduce**
1. Go to [https://dev.cugetreg.com](https://dev.cugetreg.com) (Linking to dev for now as beta seems to be broken, but I was able to replicate on beta before it broke)
2. Clear all local storage and cookies to ensure clean state
3. Click "ตั้งค่า" in the cookie banner
4. Keep the analytics cookies checkbox unchecked, and click "ยืนยัน"
5. Refresh the page
6. The cookie banner still appears

**Expected behavior**
The cookie banner should not appear after the user have chose the cookies settings.

**Screenshots**
https://user-images.githubusercontent.com/8080853/186223527-9b20634e-ec08-4c4e-ac4c-fb306eaf37c1.mov

**Desktop:**
 - OS: macOS 12.4
 - Browser: Chrome 104.0.5112.101

**Comment by bombnp** [comment]
@paphonb Please close this issue if it's done. Also use [Linking a pull request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) to automatically close issues.
