### ISSUE TITLE
[BUG] Critical Production Error: Course Detail page is down

### ISSUE THREAD

**Issue by bombnp** [thinc-org/cugetreg#395]
**Describe the bug**

Users cannot access course detail page (ex. https://cugetreg.com/S/courses/0123101). It says 500 Internal Server Error. I checked the logs in portainer in cugetreg-web, and it's like this
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/24814968/187134632-c92cece7-83ed-45d7-a011-e8ac6079bd86.png">

**To Reproduce**
1. Go to https://cugetreg.com
2. Click on a course to go to course detail
3. See error

**Expected behavior**

It should display course data as normal.

**Screenshots**

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/24814968/187135111-4e5aed60-2f32-4005-8828-2187aaf65411.png">
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/24814968/187134632-c92cece7-83ed-45d7-a011-e8ac6079bd86.png">

**Desktop (please complete the following information):**
 

**Smartphone (please complete the following information):**
 

**Additional context**

CC @saenyakorn @paphonb

**Comment by paphonb** [comment]
Temporarily rolled back to pre-migration images. Will investigate further.

**Comment by bombnp** [comment]
https://cugetreg.com/S/courses/0201103
The system is back to normal for now.

**Comment by bombnp** [comment]
wait why is this not closed lol.

Have u tried reverting the revert in infra? @paphonb

**Comment by bombnp** [comment]
seems fixed, i'll close for now
