### ISSUE TITLE
[BACKLOG] Rename monorepo apps prefix

### ISSUE THREAD

**Issue by bombnp** [thinc-org/cugetreg#430]
### Problem

why the hell do we have `cugetreg-` in front of every app what the fuck

### Task Description

remove that `cugetreg-`

### Additional Context

requested by @Leomotors 

### Related Teams

- [ ] Frontend
- [ ] Backend
- [ ] Data
- [ ] Design
- [ ] Infra
- [ ] QA

### Task Advisors

@bombnp

**Comment by saenyakorn** [comment]
Wait, the app name is related to the Docker image name. If you named the app `web` or `api` the image name would be just `web` and `api`

**Comment by saenyakorn** [comment]
The app name = the image name already makes sense

**Comment by paphonb** [comment]
> Wait, the app name is related to the Docker image name. If you named the app `web` or `api` the image name would be just `web` and `api`

For Docker, we can just prefix it when building the image. Or do something like `ghcr.io/thinc-org/cugetreg/web`.
I like short app names better. It would save time typing commands without the unnecessary prefixes.
