### ISSUE TITLE
[FEATURE] Change OAuth login behavior 

### ISSUE THREAD

**Issue by saenyakorn** [thinc-org/cugetreg#436]
**Is your feature request related to a problem? Please describe.**

To engage users to login into our website, we need to change our login flow. in order to collect more data for data team.

**Describe the solution you'd like**

Google allows us to popup the login dialog like this 

<img width="412" alt="Screen Shot 2565-11-28 at 12 00 32" src="https://user-images.githubusercontent.com/33742791/204197566-36b6e548-39f7-4912-92df-78964b853312.png">

**Describe alternatives you've considered**

**Additional context**

**Comment by saenyakorn** [comment]
https://piraces.dev/posts/how-to-use-google-one-tap/

**Comment by suphon-t** [comment]
We actually considered using Google One Tap in the past, but we couldn’t find a way to go set the hostedDomain argument (only allowing logins from student.chula.ac.th) in the new JavaScript SDK. 

I don’t know if this is still the case, but if it is, and we really want to use One Tap, then we would have to find another way to verify that the user is a Chula student before reviewing courses.

**Comment by saengowp** [comment]
Yea. It is UX problem mostly. We can check that user is not student.chula only after they tapped.

**Comment by tithanayut** [comment]
I have tried creating a client credential in Chula Google Cloud tenant and configured the consent settings to only allow internal users.

It seems that Google Sign-in Library still lists all Google Accounts in the prompt and only denies access after the user has selected non-organization accounts

![image](https://user-images.githubusercontent.com/30551284/211457284-a6751b9c-1210-4919-854b-3e19503991db.png)

So this is indeed a UX problem. Will try to see if there are other alternatives.

**Comment by bombnp** [comment]
https://github.com/MomenSherif/react-oauth#googlelogin

there seems to be a way to provide hosted domain hints to the one tap prompt tho.

**Comment by tithanayut** [comment]
There is no mention of that in official SDK. WIll try this one.

**Comment by bombnp** [comment]
> There is no mention of that in official SDK. WIll try this one.

what about this? https://developers.google.com/identity/openid-connect/openid-connect#hd-param

**Comment by saengowp** [comment]
They seems to use undocumented `hosted_domain` params. Interesting.

**Comment by tithanayut** [comment]
> > There is no mention of that in official SDK. WIll try this one.
> 
> what about this? https://developers.google.com/identity/openid-connect/openid-connect#hd-param

That is for the OAuth authorization code flow. One Tap sign-in is done through the Google Sign-In JavaScript library.

**Comment by tithanayut** [comment]
> They seems to use undocumented `hosted_domain` params. Interesting.

It seems that some other params are undocumented too.
Here is for `log_level` https://stackoverflow.com/a/72883451/229792
No so good.

**Comment by tithanayut** [comment]
Anyway, I managed to use that undocumented `hosted_domain` param in #488 and it works on my side. Will wait for the dev environment to work before finalizing the PR.

**Comment by bombnp** [comment]
@tithanayut the prompt still pops up even if I'm logged in. Is there a way to make the prompt not appear if logged in?
<img width="536" alt="image" src="https://user-images.githubusercontent.com/24814968/216874681-9b65f468-ca02-4019-b8cd-b39674624ea4.png">

**Comment by tithanayut** [comment]
Can you provide the steps to replicate? I can't reproduce that on my machine. The following code already check for login status before prompt.

https://github.com/thinc-org/cugetreg/blob/487bb549383971e24f8bbf43b61ba1e8bef1f54d/apps/web/src/common/components/GoogleOneTapPrompt/hooks/useGoogleOneTap/index.ts#L26-L28

**Comment by tithanayut** [comment]
I guess #507
