### ISSUE TITLE
[FEATURE] Analytic Discord Bot Notification

### ISSUE THREAD

**Issue by PongDev** [thinc-org/cugetreg#457]
**Is your feature request related to a problem? Please describe.**

About Analytic Discord Bot, should we report it daily or weekly. It can pull a lot of data should we display in text format? or image.
**Describe the solution you'd like**

Decision problem of what metrics/dimension and time scope for analytic to report to us.
**Describe alternatives you've considered**

Basic method is display only daily active user, however I think analytic bot can provided us more information than only this.
**Additional context**

**Comment by bombnp** [comment]
Is this a question of #439? If so, put it there instead of opening a new issue.

**Comment by saenyakorn** [comment]
Duplicated #439
