### ISSUE TITLE
[FEATURE] อัพเดตข้อมูล

### ISSUE THREAD

**Issue by saenyakorn** [thinc-org/cugetreg#586]
Automated generating issues from Airtable Form

**Describe the bug**

**Expected Result**
พอดีตอนนี้ทางระบบ reg chula ได้มีการอัพเดตข้อมูลรายวิชาในปี 2566 แล้ว จึงอยากให้อัพเดตข้อมูลค่ะ เพราะมีบางรายวิชาที่เปลี่ยนวิชาเรียน

**Screenshots**

**Platform**

**Link**
https://airtable.com/appDUOJ3KIOgYiYZy/tblZN3cqxnEzZNpWp/recvCaPplHdG7fSNi

**Comment by bombnp** [comment]
fixed by #587
