### ISSUE TITLE
[FEATURE] อัปเดตข้อมูลของรายวิชา 2759362 การปรับพฤติกรรมผู้เรียน (2566/2)

### ISSUE THREAD

**Issue by saenyakorn** [thinc-org/cugetreg#653]
Automated generating issues from Airtable Form

**Describe the bug**

**Expected Result**
เนื่องจากตอนนี้ทางรายวิชาได้อัปเดตข้อมูล
โดยเพิ่มตอนเรียนที่ 2 วันจันทร์ เวลา 09:00 - 12:00 น. เรียนที่อาคาร 3
(แต่ห้องเรียนจะประกาศในภายหลังผ่านทาง CU reg)
อยากให้ทางเจ้าหน้าที่ตรวจสอบและอัปเดตข้อมูลด้วยนะคะ ขอบคุณค่ะ

**Screenshots**
Screenshot (297).png

**Platform**

**Link**
https://airtable.com/appDUOJ3KIOgYiYZy/tblZN3cqxnEzZNpWp/recwbttSgYf25TDqF

**Comment by Leomotors** [comment]
Data is updated daily,
checked.
