### ISSUE TITLE
[BUG] ลอคอินเมลล์จุฬาไม่ได้

### ISSUE THREAD

**Issue by saenyakorn** [thinc-org/cugetreg#663]
Automated generating issues from Airtable Form

**Describe the bug**
จะลอคอินเพื่อดูตารางเรียนในวิชาที่ได้ลงไป แต่มันขึ้นว่า This account has been disable
เป็นทั้งคอม มือถือ ไอแพด

**Expected Result**

**Screenshots**
FE1A2E6B-6E22-446E-A953-4BFA3244C6BA.png

**Platform**
คอมพิวเตอร์

**Link**
https://airtable.com/appDUOJ3KIOgYiYZy/tblZN3cqxnEzZNpWp/reclgylvO8hcFkAKu

**Comment by leomotors** [comment]
Not problem on our side
