### ISSUE TITLE
[FEATURE] เพิ่มข้อมูลรายวิชาเรียน ปีการศึกษา 2567 ภาคต้นและภาคปลาย

### ISSUE THREAD

**Issue by saenyakorn** [thinc-org/cugetreg#680]
Automated generating issues from Airtable Form

**Describe the bug**

**Expected Result**
สวัสดีค่ะ นิสิตมีข้อสงสัยว่าทางทีมงานจะเพิ่มข้อมูลรายวิชาดังหัวข้อเมื่อไหร่คะ

**Screenshots**

**Platform**

**Link**
https://airtable.com/appDUOJ3KIOgYiYZy/tblZN3cqxnEzZNpWp/recfaS60Bfh31Ann9

**Comment by leomotors** [comment]
Updated scraper config to scrape 2567, will update frontend once data arrived

**Comment by leomotors** [comment]
I guess we can mark this as done
