### ISSUE TITLE
[FEATURE] เพิ่มหัวข้อปีการศึกษา 1/2567

### ISSUE THREAD

**Issue by saenyakorn** [thinc-org/cugetreg#681]
Automated generating issues from Airtable Form

**Describe the bug**

**Expected Result**
ไม่ทราบว่าทางแอดมินมีกำหนดเพิ่มหัวข้อสำหรับปีการศึกษาเทอมต้น 2567 ตอนไหนหรอครับ พอดีว่าอยากจะจัดตารางหารายวิชามาลงครับ พอดีว่าคิดหนักเลือกลงไม่ถูก มองไม่เห็นภาพ 555555 ยังไงรบกวนทางแอดมินด้วยนะครับ ขอบคุณครับ

**Screenshots**

**Platform**

**Link**
https://airtable.com/appDUOJ3KIOgYiYZy/tblZN3cqxnEzZNpWp/recuUNXzfHXZrJKId

**Comment by leomotors** [comment]
#680
